export const SLUGS = [
  "uwreflection",
  "flowboard",
  "uoguelphcourses",
  "arcki",
  "transit-flow",
  "uog-webring",
  "triploom",
  "octree",
  "converge",
  "echolag",
  "uogreflection",
  "footy",
  "hackathons",
  "soccer-stats",
  "code-keeper",
  "text-anxiety",
  "htv",
  "jachacks",
  "terrahacks",
  "hc26",
] as const;
